spring:
  thymeleaf:
    cache: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    excluded-view-names:
    template-resolver-order:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://115.159.108.79:3306/migu?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: asd123456
    initialize: true
  init-db: true
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8081